name: Test Workflow
on: [workflow_dispatch]

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Something
        run: |
            echo "Something"
            echo "Something again"
      - name: Print finish
        run: echo "Finish"
